### ISSUE TITLE
Set up deployment flow

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/pendulum-squids#3]
We want to set up a proper deployment flow that makes us able to deploy the squids easily.
It seems like subsquid recently introduced so-called [organizations](https://docs.subsquid.io/deploy-squid/organizations/). 
This is a great feature because then we don't rely on single entities to deploy squids but we can share this responsibility between all developers. 

## Todo
- [x] Investigate how we can deploy squids to our `pendulum` organization. 
- [x] Add information about how to deploy the squid for each network to the README
- [x] Make sure that the deployment of the squid to foucoco and amplitude works properly
